Remove sendEOF and adjust myPatchNewLine
The "myPatchNewline" code in WinPTYOutputStream converts an LF character
to CRLF.  Converting it to CR makes much more sense.  winpty interprets
LF as Ctrl-RETURN rather than RETURN, and it interprets CRLF as two
keypresses (RETURN followed by Ctrl-RETURN).

e.g. Here's what myPatchNewline looked like using WINPTY_DEBUG=trace,input
and writing "dir\n" to the WinPTYOutputStream:

[70868.092 winpty-agent.exe,p8848,t8228]: input chars: dir^M^J (64 69 72 0D 0A)
[70868.092 winpty-agent.exe,p8848,t8228]: keypress: D ch='d'
[70868.092 winpty-agent.exe,p8848,t8228]: keypress: I ch='i'
[70868.092 winpty-agent.exe,p8848,t8228]: keypress: R ch='r'
[70868.092 winpty-agent.exe,p8848,t8228]: keypress: RETURN ch=0xd
[70868.092 winpty-agent.exe,p8848,t8228]: keypress: LCtrl-RETURN ch=0xa

Aside: it's possible winpty should change its behavior here.  I discovered
that mintty generates LF for Shift-RETURN, but I didn't find any other
terminal that ever generated LF.  They always generate CR for RETURN.  I
ought to test what happens on Unix when I open a master pty fd and send
an LF.  With mintty, pressing Shift-RETURN seemed to do the same thing as
RETURN.  The same was true inside a cmd.exe console session (but not
PowerShell; see below).  I think pty4j's users aren't typically *trying*
to press Shift-RETURN; they're just using LF because it's more familiar
than CR.

sendEOF is also strange.  The text it's writing is interpreted as three
ordinary keypresses:

[70543.707 winpty-agent.exe,p3744,t2136]: input chars: ^Z^J (5E 5A 0A)
[70543.708 winpty-agent.exe,p3744,t2136]: keypress: Shift-6 ch='^'
[70543.708 winpty-agent.exe,p3744,t2136]: keypress: Shift-Z ch='Z'
[70543.708 winpty-agent.exe,p3744,t2136]: keypress: LCtrl-RETURN ch=0xa

I don't think I've ever seen a Windows program that interpreted these
keystrokes as "exit the program".  I tried a few programs:

 * cmd.exe: The Ctrl-RETURN doesn't do anything, so it sits waiting for
   more input.  Pressing normal RETURN gives:
        'Z' is not recognized as an internal or external command,
        operable program or batch file.

 * powershell.exe: Ctrl-RETURN and Shift-RETURN are handled specially.
   They move to the next line without executing the existing line(s).
   Normal RETURN gives:
        ^Z : The term '^Z' is not recognized as the name of a cmdlet,
        function, script file, or operable program.

 * python.exe: Ctrl-RETURN does nothing, like cmd.exe.  Normal RETURN gives
   an error:
        >>> ^Z
          File "<stdin>", line 1
            ^Z
            ^
        SyntaxError: invalid syntax

 * wmic.exe: Again, Ctrl-RETURN does nothing, but otherwise:
        wmic:root\cli>^Z
        ^Z - Alias not found.

I tested by testing by typing (Shift-6, Shift-Z, Ctrl-RETURN).  winpty
would tend to submit all three keypresses in a single WriteConsoleInput
call, but that seems unlikely to matter.